### ISSUE TITLE
Padding increase on search results

### ISSUE THREAD

**Issue by jakobjohansson** [smallcolin/iceland_family_tree#1]
When using the search function, the results appear in a box with an image and a field for the name

<img width="331" alt="screen shot 2017-09-20 at 13 03 03" src="https://user-images.githubusercontent.com/21201123/30640703-35c6d64c-9e04-11e7-982b-565d99db747e.png">

This name field could probably have some more lower and upper padding in my opinion.

**Comment by smallcolin** [comment]
![screen shot 2017-09-27 at 11 05 33](https://user-images.githubusercontent.com/24314379/30904980-d6841c24-a373-11e7-8a85-bf0cc8d0ea9e.jpg)

Better?

**Comment by jakobjohansson** [comment]
Lovely
